### PR TITLE
Changed tinymce plugin font size to be consistent with default FOX text size

### PR DESCRIPTION
**Pull request by tombasche**

### CODE REVIEW

**Comment by Palmr** [comment]
Hi @tombasche, thanks for the changes.

You shouldn't be modifying the minified TinyMCE javascript however. When we upgrade TinyMCE that change will be lost.
Ideally the CSS rule should be overwritten in the FOX CSS or the TinyMCE skin CSS, whatever works.

**Comment by tombasche** [comment]
Cheers @Palmr 
Changes to the js have been reverted and it's in the TinyMCE skin CSS now :)

**Comment by Palmr** [comment]
Cheers @tombasche for the change.
Things are a little busy here at the moment so will try this in a local build in the next day or two before merging if that's okay?

**Comment by tombasche** [comment]
Sounds good

**Pull request merged**
